### ISSUE TITLE
fespi flash driver option 0x10014000

### ISSUE THREAD

**Issue by hubbsvtgc** [psherman42/Demystifying-OpenOCD#1]
The flash command below passes the value 0x10014000 to fespi driver.
How this value is arrived?

flash bank spi0 fespi 0x20000000 0 0 0 riscv.cpu.0 0x10014000

**Comment by psherman42** [comment]
The value 0x10014000 is specific to the FE310-G00x chip [SiFive], and particularly to the wiring of the hardware demonstrations of, e.g., [HiFive](https://sifive.cdn.prismic.io/sifive/c34f4c7f-0d3a-493e-8a19-a0b18f8a4555_hifive1-b01-schematics.pdf) (see U5 on Sheet 3) and [LoFive](https://github.com/mwelling/lofive/blob/master/lofive.pdf) (see U2), and similar boards.

It points to a memory-mapped I/O port where there's a device which responds to the standard memory Read Data command 0x03.

This value, 0x10014000, comes from the memory map location of the QSPI0 device I/O port as shown in Table 62 of the [FE310 Manual](https://sifive.cdn.prismic.io/sifive/b56b304f-cd2d-421b-9c14-6b35c33f172e_fe310-g002-manual-v1p4.pdf).

If, for example, you designed a board where your instruction memory chip was single-line (not quad-line) wired, using the third SPI device I/O port, then this value for the fespi command would instead be 0x10034000.

Notes: Referring to the [flash bank](https://www.openocd.org/doc/html/Flash-Commands.html) command,
- Don't confuse "Name", the first argument of the _flash bank_ command, with the device peripheral; it's only a vanity name.
- The third argument, "Base", is where the instruction memory device's data is presented in the SoC's memory map; this is different from the memory location(s) where the device makes and responds to commands (see below).
- The eighth argument is a "driver-specific option" for the target memory device's command port.
- The fespi implementation is shown in [fespi.c](https://openocd.org/doc/doxygen/html/fespi_8c_source.html)
